//import UserContractListContainer from './containers/UserContractListContainer';
//import StaffContractListContainer from "ROUTES/Contract/containers/StaffContractListContainer";
import TestCaseListContainer from "./containers/TestCaseListContainer";
import TestRecordListContainer from "./containers/TestRecordListContainer";
import TestProblemListContainer from "./containers/TestProblemListContainer";
import TestPlanListContainer from "./containers/TestPlanListContainer";
import TestCaseContentContainer from "./containers/TestCaseContentContainer";
import TestRecordContentContainer from "./containers/TestRecordContentContainer";
import TestProblemContentContainer from "./containers/TestProblemContentContainer";
import TestPlanContentContainer from "./containers/TestPlanContentContainer";

//export const UserContractListView = UserContractListContainer;
//export const StaffContractListView = StaffContractListContainer;
export const TestCaseListView = TestCaseListContainer;
export const TestRecordListView = TestRecordListContainer;
export const TestProblemListView = TestProblemListContainer;
export const TestPlanListView = TestPlanListContainer;
export const TestCaseContentView = TestCaseContentContainer;
export const TestRecordContentView = TestRecordContentContainer;
export const TestProblemContentView = TestProblemContentContainer;
export const TestPlanContentView = TestPlanContentContainer;
