INSERT INTO `tbl_sys_projects` (`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`USER_ID`,`CONSIGN_ID`,`CONTRACT_ID`,`TESTREPORT_ID`,`TESTREPORTCHECK_ID`,`TESTWORKCHECK_ID`,`TESTPLAN_ID`,`SATISFACTIONSURVEY_ID`) VALUES
('test',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


