INSERT INTO `tbl_sys_contracts` (`CONTRACTBODY`,`PROCESS_INSTANCE_ID`,`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`USER_ID`) VALUES
('contract1 belong to consign1','project1','contract1',NULL,NULL,NULL,NULL,NULL,NULL,'2'),
('contract2 belong to consign2','project2','contract2',NULL,NULL,NULL,NULL,NULL,NULL,'2'),
('contract3 belong to consign3','project3','contract3',NULL,NULL,NULL,NULL,NULL,NULL,'3');

INSERT INTO `tbl_sys_testreports`(`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`BODY`) VALUES
('tr1',NULL,NULL,NULL,NULL,NULL,NULL,'testReport1'),
('tr2',NULL,NULL,NULL,NULL,NULL,NULL,'testReport2'),
('tr3',NULL,NULL,NULL,NULL,NULL,NULL,'testReport3');

INSERT INTO `tbl_sys_projects` (`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`USER_ID`,`CONSIGN_ID`,`CONTRACT_ID`,`TESTREPORT_ID`) VALUES
('p1',NULL,'project1',NULL,NULL,NULL,NULL,'2','1','contract1','tr1'),
('p2',NULL,'project2',NULL,NULL,NULL,NULL,'2','2','contract2','tr2'),
('p3',NULL,'project3',NULL,NULL,NULL,NULL,'3','3','contract3','tr3');

INSERT INTO `tbl_sys_testbugs` (`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`PROCESS_INSTANCE_ID`,`PROJECT_ID`,`BODY`,`CREATED_USER_NAME`,`ALTERED_USER_NAME`)VALUES
('tb1',NULL ,NULL,NULL,NULL,NULL,NULL,'TestBug1',NULL,'TestBug_1',NULL ,NULL ),
('tb2',NULL ,NULL,NULL,NULL,NULL,NULL,'Testbug2',NULL ,'TestBug_2',NULL ,NULL ),
('tb3',NULL ,NULL,NULL,NULL,NULL,NULL,'Testbug3',NULL,'TestBug_3',NULL ,NULL );

INSERT INTO `tbl_sys_testplans` (`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`PROCESS_INSTANCE_ID`,`ALTERED_USER_ID`,`BODY`,`CREATED_USER_NAME`,`ALTERED_USER_NAME`)VALUES
('tp1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tp2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tp3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL );

INSERT INTO `tbl_sys_consigns` (`CONSIGNATION`,`PROCESS_INSTANCE_ID`,`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`USER_ID`)VALUES
('consign1 belong to project1','porject1','consign1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,'1' ),
('consign2 belong to project1','porject2','consign2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,'2' ),
('consign3 belong to project1','porject3','consign3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,'3' );

INSERT INTO `tbl_sys_testrecords` (`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`BODY`,`PROJECT_ID`,`PROCESS_INSTANCE_ID`,`TESTCASE_ID`,`CREATED_USER_NAME`,`ALTERED_USER_NAME`)values
('tr1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tr2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tr3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL );

INSERT INTO `tbl_sys_testworkchecks`(`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`BODY`,`SOFTWARENAME`,`VERSION`,`CLIENT`,`STARTTIME`,`FCENDTIME`,`TESTWORKER`,`PROCESS_INSTANCE_ID`,`ACENDTIME`,`CREATED_USER_NAME`,`ALTERED_USER_NAME`)VALUES
('tec1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL, ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL),
('tec2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL, ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL),
('tec3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL, ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL);

INSERT INTO `tbl_sys_testreports` (`ID`,`CODE`,`NAME`,`CREATED_TIME`,`CREATED_USER_ID`,`ALTERED_TIME`,`ALTERED_USER_ID`,`PROCESS_INSTANCE_ID`,`BODY`,`CREATED_USER_NAME`,`ALTERED_USER_NAME`) VALUES
('tp1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tp2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tp3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL );

INSERT INTO `tbl_sys_satisfactionsurveys` (ID, CODE, NAME, CREATED_TIME, CREATED_USER_ID, ALTERED_TIME, ALTERED_USER_ID, PROCESS_INSTANCE_ID, BODY, CREATED_USER_NAME, ALTERED_USER_NAME) VALUES
('ss1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('ss2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('ss3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL );

INSERT INTO `tbl_sys_testreportchecks`  (ID, CODE, NAME, CREATED_TIME, CREATED_USER_ID, ALTERED_TIME, ALTERED_USER_ID, PROCESS_INSTANCE_ID, BODY, CREATED_USER_NAME, ALTERED_USER_NAME) VALUES
('trc1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('trc2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('trc3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL );

INSERT INTO `tbl_sys_testfunctions` (ID, CODE, NAME, CREATED_TIME, CREATED_USER_ID, ALTERED_TIME, ALTERED_USER_ID, PROCESS_INSTANCE_ID, PROJECT_ID, BODY, CREATED_USER_NAME, ALTERED_USER_NAME) VALUES
('tf1',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tf2',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ),
('tf3',NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL ,NULL );
